version: '3.8'

services:
  backend:
    build:
      context: ./backend  # Path to your backend directory
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - frontend
      - mongo
    environment:
      WAIT_HOSTS: frontend:3000, mongo:27017
      MONGO_URI: mongodb://myuser:mypassword@mongo:27017/mydatabase

  frontend:
    build:
      context: ./frontend  # Path to your frontend directory
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  mongo:
    image: mongo:5
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

volumes:
  mongo-data:
